name: Bug Report
description: Report a bug in PrimeCodex
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide the following information to help us diagnose and fix the issue.

  - type: input
    id: version
    attributes:
      label: PrimeCodex Version
      description: What version of PrimeCodex are you using?
      placeholder: "e.g., 0.1.0, latest commit hash"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., Ubuntu 20.04, macOS 13.0, Windows 11]
        - Python version: [e.g., 3.11.2]
        - Virtual environment: [yes/no]
        - OpenAI API: [configured/not configured]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or stack traces
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove any secrets!)
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem