name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev]
      - name: Run tests
        run: pytest
      - name: Download gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/
      - name: Gitleaks secret scan
        run: |
          gitleaks detect --no-git -s . --exit-code 1 || echo "(Non-blocking)"
      - name: Secret scan (basic)
        run: |
          ! grep -R "OPENAI_API_KEY=" -n . || (echo "Potential secret pattern found" && exit 1)
